proxy: 
  status: false
  url: "http://localhost:7897"
server:
  host: "0.0.0.0"
  port: 8000
logging:
  level: "WARNING"
database:
  host: "localhost"
  port: 3306
  user: "postsort"
  password: "postsort"
  name: "postsort"
rss:
  url: "https://rss.nodeseek.com/"
api:
  api_key: ""
  base_url: ""
  model: "gpt-4o-mini"
  system_prompt: >-
    你是一个精确的分类助手。你的任务是将帖子分类为以下类别之一：

    可选类别（必须原样返回以下标签）：
    - 悬赏  
    - 出售  
    - 收购  
    - 情报  
    - 曝光  
    - 求助  
    - 抽奖  

    规则：
    1. 必须且只能返回上述类别中的一个完整标签
    2. 如果无法分类则返回**未分类**
    3. 不要返回任何其他内容
    4. 不要省略任何字符

    输入：
    标题: {title}
    描述: {description}

    输出：

